export {default as Home} from './Home'
export {default as Login} from './Login'
export {default as Registrar} from './Registrar'
export {default as Leads} from './Leads'
export {default as Perfil} from './Perfil'
